"""Compile an ExecutionPlan into a Jenkinsfile (Batch 8, Task C; Section 12).

Same invariants as the GitHub/GitLab compilers:

* **allow-listed commands only** — every ``sh`` step is a verbatim
  CommandTemplateRegistry lookup;
* **report artifacts** — stages in ``REPORT_UPLOAD_STAGES`` are archived
  (``archiveArtifacts``) under the SAME ``ci-agent-scan-<stage_id>`` names;
* **no credentials** — the generated pipeline must never reference
  ``withCredentials`` or credential bindings; a textual guard hard-fails.

DOCUMENTED DEVIATION (NOTES.md): Jenkins declarative pipelines have no
cross-stage ``needs:`` DAG. Stages are emitted in the Planner's deterministic
TOPOLOGICAL order (sequential execution), which preserves every dependency
edge's ordering guarantee — a strictly safer (slower) schedule, never an
incorrect one.
"""

from __future__ import annotations

from ci_agent.adapters.github_actions.command_template_registry import CommandTemplateRegistry
from ci_agent.adapters.github_actions.compiler import (
    CHECKOUT_TEMPLATE_ID,
    REPORT_UPLOAD_STAGES,
)
from ci_agent.core.models.execution_plan import ExecutionPlan

JENKINSFILE_NAME = "Jenkinsfile"
GATE_TOOL_PREFIX = "internal."

# Publish target: a Jenkins build parameter / node environment variable
# (configuration, not secret).
PUBLISH_ENV_NAME = "CI_AGENT_PUBLISH_REF"

_FORBIDDEN_FRAGMENTS = (
    "withCredentials",
    "secrets.",
    "$GITLAB_TOKEN",
    "PRIVATE-TOKEN",
    "glpat-",
)


def _groq_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def compile_to_jenkinsfile(
    plan: ExecutionPlan,
    registry: CommandTemplateRegistry | None = None,
) -> str:
    """Compile ``plan`` into a declarative Jenkinsfile (topological order)."""
    registry = registry or CommandTemplateRegistry()

    lines: list[str] = [
        "// Generated by ci-agent — allow-listed steps only (Section 7.3).",
        "pipeline {",
        "    agent any",
        f"    environment {{ {PUBLISH_ENV_NAME} = '${{{PUBLISH_ENV_NAME}}}' }}",
        "    options { timestamps() skipStagesAfterUnstable() }",
        "    stages {",
    ]
    for step in plan.resolved_steps:  # already topological (Planner)
        stage_id = step.stage_id
        lines.append(f"        stage('{_groq_escape(stage_id)}') {{")
        lines.append("            steps {")
        if step.container_image:
            # Declarative per-stage containers need plugins; the stage label
            # records the pinned image for audit instead (NOTES.md deviation).
            lines.append(
                f"                echo '[{stage_id}] image {_groq_escape(step.container_image)}'"
            )
        if step.tool_name.startswith(GATE_TOOL_PREFIX):
            lines.append(
                f"                echo '[{stage_id}] {step.tool_name} orchestrated"
                " by ci-agent control plane'"
            )
        elif step.command_template_id == CHECKOUT_TEMPLATE_ID:
            # Native handling: the Jenkins job's SCM section performs the
            # checkout; the stage is the correlation marker.
            lines.append(
                f"                echo '[{stage_id}] checkout performed natively"
                " by the Jenkins job SCM'"
            )
        else:
            command = registry.get_command(step.command_template_id)
            if command is None:
                # Fail-closed: an unknown template id can never compile.
                raise ValueError(
                    f"no allow-listed command for template {step.command_template_id!r}"
                )
            escaped = command.replace("'", "'\\''")
            lines.append("                sh '''")
            lines.append("                    set +e")
            lines.append(f"                    {escaped}")
            lines.append("                    code=$?")
            lines.append('                    echo "exit_code=$code" >> ci_agent_exit_code.txt')
            lines.append("                    exit $code")
            lines.append("                '''")
        if stage_id in REPORT_UPLOAD_STAGES:
            paths = ", ".join(f"'{p}'" for p in REPORT_UPLOAD_STAGES[stage_id])
            lines.append(
                "                archiveArtifacts artifacts: [" + paths + "], "
                "allowEmptyArchive: true"
            )
        lines.append("            }")
        lines.append("        }")
    lines.append("    }")
    lines.append("}")
    text = "\n".join(lines) + "\n"

    for fragment in _FORBIDDEN_FRAGMENTS:
        if fragment in text:
            raise ValueError(
                f"compiled Jenkinsfile references credential-shaped fragment "
                f"{fragment!r} — the agent never injects credentials (Section 7.3)"
            )
    return text


__all__ = ["JENKINSFILE_NAME", "PUBLISH_ENV_NAME", "compile_to_jenkinsfile"]
